### ISSUE TITLE
Using pnpm, vite-plugin-dynamic-import Cannot find module 'vite'

### ISSUE THREAD

**Issue by stereokai** [vite-plugin/vite-plugin-dynamic-import#35]
```
failed to load config from /Users/toma/dev/multi-charts-comparison/vite.config.js
error when starting dev server:
Error: Cannot find module 'vite'
Require stack:
- /Users/toma/Library/pnpm/global/5/node_modules/vite-plugin-dynamic-import@1.2.2/node_modules/vite-plugin-dynamic-import/dist/index.js
- /Users/toma/dev/multi-charts-comparison/vite.config.js
- /Users/toma/Library/pnpm/global/5/node_modules/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js
- /Users/toma/Library/pnpm/global/5/node_modules/vite@2.9.15/node_modules/vite/dist/node/cli.js
- /Users/toma/Library/pnpm/global/5/node_modules/vite@2.9.15/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Module.<anonymous> (/Users/toma/Library/pnpm/global/5/node_modules/vite-plugin-dynamic-import@1.2.2/node_modules/vite-plugin-dynamic-import/dist/index.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/toma/Library/pnpm/global/5/node_modules/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:62009:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
 ELIFECYCLE  Command failed with exit code 1.

```

Hi, it's me again :)

I switched to a git branch, and now this started happening. When starting `vite dev` with pnpm, `vite-plugin-dynamic-import` can't find Vite, even though Vite is installed and is the starting point of the script... (`vite.config.js`). I tried reinstalling node_modules & tried updating versions. It only happens with pnpm. Do you have an idea?

Thank you very much!

**Comment by caoxiemeihao** [comment]
Upgrade to `v1.2.3`

**Comment by stereokai** [comment]
@caoxiemeihao you are super quick!!!
Just out of curiosity, does the switch from explicit *.mjs to explicit *.cjs has any to do with the fix? Or was it only `...Object.keys(pkg.dependencies)` that did it?

Thanks!

**Comment by caoxiemeihao** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/26263658/196306662-6d04043f-3ac5-49de-90c4-390348656bf2.png">
https://github.com/vite-plugin/vite-plugin-dynamic-import/commit/ebeaaf316a5387140d035904c8c49a71b6eccb9c#diff-6e17b8e79c75c75e3252f375e881d44b415de8e8fc949bcccea81e6a511945d9L1

I implemented `normalizePath` myself instead of the one provided by Vite. 😄
